Repository kowainik/policeman, pull requests merged in 2020-01, with the labels that each got.

#9 [#1] Initial cleanup
  policeman.cabal
  src/Prelude.hs
Labels: refactoring

#10 [#2] Implement basic CLI interface
  app/Main.hs
  policeman.cabal
  src/Policeman.hs
  src/Policeman/Cli.hs
  src/Policeman/ColorTerminal.hs
  src/Policeman/Run.hs
Labels: CLI

#11 [#3] Implement Download From Hackage
  .gitignore
  policeman.cabal
  src/Policeman/Core/Package.hs
  src/Policeman/Download/Common.hs
  src/Policeman/Download/Hackage.hs
Labels: enhancement

#14 [#5] Implement Cabal files Parsing functionality
  policeman.cabal
  src/Policeman/Cabal.hs
Labels: parsing

#16 [#6] Implement Generic Diff platform
  policeman.cabal
  src/Policeman/Core/Diff.hs
  src/Policeman/Core/Package.hs
  src/Policeman/Diff.hs
Labels: diff

#17 [#15] Add basic unit tests
  policeman.cabal
  src/Policeman/Cabal.hs
  test/Spec.hs
  test/Test/Policeman/Cabal.hs
Labels: tests

#18 [#7] Implement basic Diff Evaluation
  policeman.cabal
  src/Policeman/Core/Diff.hs
  src/Policeman/Core/Package.hs
  src/Policeman/Download/Hackage.hs
  src/Policeman/Evaluate.hs
Labels: output

#23 [#20] Version roundtrip functions
  policeman.cabal
  src/Policeman/Core/Package.hs
  src/Policeman/Core/Version.hs
  src/Policeman/Download/Hackage.hs
  src/Policeman/Evaluate.hs
  test/Spec.hs
  test/Test/Policeman/Version.hs
Labels: tests

#27 [#12] Pass previous version from Hackage, connect pieces
  policeman.cabal
  src/Policeman.hs
  src/Policeman/Cabal.hs
  src/Policeman/Cli.hs
  src/Policeman/Core/Package.hs
  src/Policeman/Download/Common.hs
  src/Policeman/Download/Hackage.hs
  src/Policeman/Run.hs
Labels: CLI, enhancement, refactoring

#29 [#26] Add versionText field into Version data type
  src/Policeman/Core/Version.hs
  src/Policeman/Download/Hackage.hs
  test/Test/Policeman/Version.hs
Labels: refactoring, tests

#30 [#21] Build current and downloaded projects with HIE files generated
  policeman.cabal
  src/Policeman/Hie.hs
  src/Policeman/Run.hs
Labels: hie

#33 [#31] Translate HIE AvailInto into our data type
  policeman.cabal
  src/Policeman/Core/Hie.hs
  src/Policeman/Core/Package.hs
Labels: enhancement, hie

#34 [#22] Read all HIE files recursively
  policeman.cabal
  src/Policeman/Hie.hs
  src/Policeman/Run.hs
Labels: hie

#37 [#32] Get list of exposed modules from .cabal and create PackageStructure to calculate diff
  src/Policeman/Cabal.hs
  src/Policeman/Core/Package.hs
  src/Policeman/Hie.hs
  src/Policeman/Run.hs
Labels: diff, parsing

#39 [#36] Get export information from HIE files
  policeman.cabal
  src/Policeman/Core/Diff.hs
  src/Policeman/Core/Hie.hs
  src/Policeman/Core/Package.hs
  src/Policeman/Diff.hs
  src/Policeman/Evaluate.hs
  src/Policeman/Run.hs
Labels: hie

#40 [#38] Print pretty changes
  src/Policeman/Core/Package.hs
  src/Policeman/Diff.hs
  src/Policeman/Run.hs
Labels: output

#42 [#8] Pretty-print the output
  src/Policeman/Cabal.hs
  src/Policeman/Core/Package.hs
  src/Policeman/Diff.hs
  src/Policeman/Run.hs
Labels: output

#43 Fix HLint warnings
  src/Policeman/Core/Version.hs
  src/Policeman/Diff.hs
  test/Test/Policeman/Version.hs
Labels: refactoring

#47 [#28] Restructure CLI handling
  src/Policeman/Cli.hs
Labels: CLI

#48 [#44] Explain version bump up in the output
  src/Policeman/Diff.hs
  src/Policeman/Evaluate.hs
  src/Policeman/Run.hs
Labels: output

#49 [#41] Add automatic detection of previous version on Hackage
  policeman.cabal
  src/Policeman/Cabal.hs
  src/Policeman/Core/Version.hs
  src/Policeman/Download/Hackage.hs
  src/Policeman/Evaluate.hs
  src/Policeman/Run.hs
  test/Test/Policeman/Version.hs
Labels: enhancement

#45 [#25] Write README
  README.md
Labels: docs

#50 Simplify GitHub CI configuration
  .github/workflows/ci.yml
Labels: CI

#51 Refactor Policeman.Run a little bit
  src/Policeman/Run.hs
Labels: refactoring
